services:
  app:
    build: .
    container_name: real-estate-app
    environment:
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - real-estate-network
    restart: always

  postgres:
    image: postgres:14-alpine
    container_name: real-estate-db
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: password
      POSTGRES_DB: real_estate_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - real-estate-network
    restart: always

  nginx:
    image: nginx:alpine
    container_name: real-estate-nginx
    ports:
      - "80:80"  
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  
      - ./nginx/conf/.htpasswd:/etc/nginx/.htpasswd
    depends_on:
      - app  
    networks:
      - real-estate-network
    restart: always

networks:
  real-estate-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
